#!/usr/bin/env python3
'''
setup board.h for HPMICRO

AP_FLAKE8_CLEAN

'''

import argparse
import shlex
import re
import sys
import os
import filecmp
import pickle
import subprocess
import json

sys.path.append(os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../../../libraries/AP_HAL/hwdef/scripts'))


class HPMicroHWDef(object):

    def __init__(self, quiet=False, outdir=None, hwdef=[]):
        # lists of HPMICRO_SPIBUS buses and HPMICRO_SPIDEV devices

        self.outdir = outdir
        self.hwdef = hwdef
        self.quiet = quiet

        # dictionary of all config lines, indexed by first word
        self.config = {}

        # all config lines in order
        self.alllines = []

        # allow for extra env vars
        self.env_vars = {}

        # output lines:
        self.all_lines = []

        # integer defines
        self.intdefines = {}

        # boolean indicating whether we have read and processed self.hwdef
        self.processed_hwdefs = False
        # a set of files which have been processed to populate this object:
        self.loaded_files = set()
        # a set of files which have been generated by this object:
        self.output_files = set()

        # sensor lists
        self.imu_list = []
        self.compass_list = []
        self.baro_list = []

        # populate a stale defines map from define name to reason-it-is-bad
        self.stale_defines = self.get_stale_defines()

        # members used to ensure we don't have duplicate sensors defined:
        self.seen_BARO_lines = set()
        self.seen_COMPASS_lines = set()

        self.hwdef = hwdef
        self.hpmicro_spibus = []
        self.hpmicro_spidev = []

        # lists of HPMICRO_I2CBUS buses
        self.hpmicro_i2cbus = []

        # list of HPMICRO_SERIAL devices
        self.hpmicro_serials = []

        # list of HPMICRO_CAN devices
        self.hpmicro_can = []

        # list of HPMICRO_ADC devices
        self.hpmicro_adc = []

        # list of HPMICRO_RCOUT declarations
        self.hpmicro_rcout = []

        # list of HPMICRO_GPIO declarations
        self.hpmicro_gpio = []

    def progress(self, message):
        if self.quiet:
            return
        print(message)

    def write_device_table(self, f, description, define_name, devlist):
        '''writes out a #define which can be used as the body of a C
        structure to populate object constructor arguments'''
        if len(devlist) == 0:
            f.write(f'\n// No {description}\n')
            return

        f.write(f'\n// {description} table\n')
        f.write(f'#define {define_name} \\\n')
        f.write(',\\\n'.join([f"   {x}" for x in devlist]))
        f.write("\n")

    def get_output_path(self, relpath):
        # keep track of files we've generated. input path is relative to output.
        self.output_files.add(relpath)
        return os.path.join(self.outdir, relpath)

    def get_numeric_board_id(self):
        '''return a numeric board ID, which may require mapping a string to a
        number via board_list.txt'''
        some_id = self.get_config('APJ_BOARD_ID')
        if some_id.isnumeric():
            if self.running_in_CI():
                raise ValueError(f"Numeric board ID found ({some_id}).  Your APJ_BOARD_ID must not use a number.  Change the number to be the name of the board used in Tools/AP_Bootloader/board_types.txt")  # noqa:E501
            return some_id

        board_types_filename = "board_types.txt"
        topdir = os.path.join(os.path.dirname(os.path.realpath(__file__)), '../../../..')
        board_types_dirpath = os.path.join(topdir, "Tools", "AP_Bootloader")
        board_types_filepath = os.path.join(board_types_dirpath, board_types_filename)
        for line in open(board_types_filepath, 'r'):
            m = re.match(r"(?P<name>[-\w]+)\s+(?P<board_id>\d+)", line)
            if m is None:
                continue
            if m.group('name') == some_id:
                return m.group('board_id')

        raise ValueError("Unable to map (%s) to a board ID using %s" %
                         (some_id, board_types_filepath))

    def write_all_lines(self, hwdat):
        f = open(hwdat, 'w')
        f.write('\n'.join(self.all_lines))
        f.close()

    def write_defaulting_define(self, f, name, value):
        f.write(f"#ifndef {name}\n")
        f.write(f"#define {name} {value}\n")
        f.write("#endif\n")

    def write_define(self, f, name, value):
        f.write(f"#define {name} {value}\n")

    def write_hwdef_header(self, outfilename):
        '''write hwdef header file'''
        self.progress("Writing hwdef setup in %s" % outfilename)
        f = open(outfilename, 'w')

        f.write('''/*
 generated hardware definitions from hwdef.dat - DO NOT EDIT
*/

#pragma once

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif

''')

        self.write_hwdef_header_content(f)

        f.close()

    def get_stale_defines(self):
        '''returns a map with a stale define and a comment as to what to do about it'''
        return {
            'HAL_COMPASS_DEFAULT': 'HAL_COMPASS_DEFAULT is no longer used; remove it from your hwdef',
            'HAL_NO_GCS': 'HAL_NO_GCS is no longer used; try "define HAL_GCS_ENABLED 0"',
            'HAL_NO_LOGGING': 'HAL_NO_LOGGING is no longer used; try "define HAL_LOGGING_ENABLED 0"',
            'HAL_NO_UARTDRIVER': 'HAL_NO_UARTDRIVER is no longer used; try "define AP_HAL_UARTDRIVER_ENABLED 0"',
            'HAL_DISABLE_LOOP_DELAY': 'HAL_DISABLE_LOOP_DELAY is no longer used; try "define HAL_SCHEDULER_LOOP_DELAY_ENABLED 0"',  # noqa:E501
            'HAL_EXTERNAL_AHRS_ENABLED': 'HAL_EXTERNAL_AHRS_ENABLED is no longer used; try "define AP_EXTERNAL_AHRS_ENABLED 1"',  # noqa:E501
            'HAL_PROBE_EXTERNAL_I2C_COMPASSES': 'HAL_PROBE_EXTERNAL_I2C_COMPASSES is no longer used; try "define AP_COMPASS_PROBING_ENABLED 1"',  # noqa:E501
            'HAL_SKIP_AUTO_INTERNAL_I2C_PROBE': 'HAL_SKIP_AUTO_INTERNAL_I2C_PROBE is no longer used; try "define AP_COMPASS_INTERNAL_BUS_PROBING_ENABLED 0',  # noqa:E501
            'HAL_COMPASS_DISABLE_IST8310_INTERNAL_PROBE': 'HAL_COMPASS_DISABLE_IST8310_INTERNAL_PROBE is no longer used; try "define AP_COMPASS_IST8310_INTERNAL_BUS_PROBING_ENABLED 0"',  # noqa:E501
            'BOARD_PWM_COUNT_DEFAULT': 'BOARD_PWM_COUNT_DEFAULT is no longer used; remove it from your hwdef files',
        }

    def write_env_py(self, filename):
        '''write out env.py for environment variables to control the build process'''
        pickle.dump(self.env_vars, open(filename, "wb"))

    def get_config(self, name, column=0, required=True, default=None, type=None, spaces=False, aslist=False):
        '''get a value from config dictionary'''
        if name not in self.config:
            if required and default is None:
                self.error("missing required value %s in hwdef.dat" % name)
            return default
        if aslist:
            return self.config[name]
        if len(self.config[name]) < column + 1:
            if not required:
                return None
            self.error("missing required value %s in hwdef.dat (column %u)" %
                       (name, column))
        if spaces:
            ret = ' '.join(self.config[name][column:])
        else:
            ret = self.config[name][column]

        if type is not None:
            if type == int and ret.startswith('0x'):
                try:
                    ret = int(ret, 16)
                except Exception:
                    self.error("Badly formed config value %s (got %s)" % (name, ret))
            else:
                try:
                    ret = type(ret)
                except Exception:
                    self.error("Badly formed config value %s (got %s)" % (name, ret))
        return ret

    def write_hwdef_header_content(self, f):
        for d in self.alllines:
            if d.startswith('define '):
                f.write('#define %s\n' % d[7:])

        self.write_SPI_config(f)
        self.write_I2C_config(f)
        self.write_SERIAL_config(f)
        self.write_CAN_config(f)

        self.write_RCOUT_config(f)
        self.write_ADC_config(f)
        self.write_GPIO_config(f)

        self.write_env_py(os.path.join(self.outdir, "env.py"))

        # Try to compute HAL_HPM storage symbols by invoking compute_storage_symbols.py
        try:
            # determine board name from alllines
            board_name = None
            for d in self.alllines:
                m = re.match(r"define\s+HAL_HPM_BOARD_NAME\s+(.*)", d)
                if m:
                    bn = m.group(1).strip()
                    # strip quotes if present
                    if bn.startswith('"') and bn.endswith('"'):
                        bn = bn[1:-1]
                    board_name = bn
                    break

            if board_name:
                # locate compute script relative to this file
                script_path = os.path.normpath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', '..', 'boards', 'compute_storage_symbols.py'))
                if os.path.exists(script_path):
                    # run script and parse JSON lines
                    proc = subprocess.run([sys.executable, script_path], capture_output=True, text=True)
                    if proc.returncode == 0 and proc.stdout:
                        for line in proc.stdout.splitlines():
                            try:
                                j = json.loads(line)
                            except Exception:
                                continue
                            if j.get('board') == board_name:
                                suggestion = j.get('suggestion', {})
                                base = suggestion.get('HAL_HPM_STORAGE_FLASH_BASE_ADDR')
                                off = suggestion.get('HAL_HPM_STORAGE_OFFSET_ADDR')
                                if base and off:
                                    # write overrides to hwdef.h
                                    f.write('\n#undef HAL_HPM_STORAGE_FLASH_BASE_ADDR\n')
                                    f.write(f'#define HAL_HPM_STORAGE_FLASH_BASE_ADDR {base}\n')
                                    f.write('\n#undef HAL_HPM_STORAGE_OFFSET_ADDR\n')
                                    f.write(f'#define HAL_HPM_STORAGE_OFFSET_ADDR {off}\n')
                                break
        except Exception:
            # do not fail the whole generation if compute script fails
            pass

    def process_line(self, line, depth):
        '''process one line of pin definition file'''
        # keep all config lines for later use
        self.all_lines.append(line)
        self.alllines.append(line)

        a = shlex.split(line, posix=False)
        if a[0] == 'HPMICRO_I2CBUS':
            self.process_line_hpmicro_i2cbus(line, depth, a)

        if a[0] == 'HPMICRO_SPIBUS':
            self.process_line_hpmicro_spibus(line, depth, a)
        if a[0] == 'HPMICRO_SPIDEV':
            self.process_line_hpmicro_spidev(line, depth, a)

        if a[0] == 'HPMICRO_SERIAL':
            self.process_line_hpmicro_serial(line, depth, a)

        if a[0] == 'CAN_ORDER':
            self.process_line_hpmicro_can(line, depth, a)

        if a[0] == 'HPMICRO_ADCPIN':
            self.process_line_hpmicro_adc(line, depth, a)

        if a[0] == 'HPMICRO_RCOUT':
            self.process_line_hpmicro_rcout(line, depth, a)

        if a[0] == 'HPMICRO_GPIO':
            self.process_line_hpmicro_gpio(line, depth, a)

        if a[0] == 'env':
            self.progress("Adding environment %s" % ' '.join(a[1:]))
            if len(a[1:]) < 2:
                self.error("Bad env line for %s" % a[0])
            name = a[1]
            value = ' '.join(a[2:])
            self.env_vars[name] = value

    # HPMICRO_I2CBUS support:
    def process_line_hpmicro_i2cbus(self, line, depth, a):
        self.hpmicro_i2cbus.append(a[1:])

    def write_I2C_bus_table(self, f):
        '''write I2C bus table'''
        buslist = []
        for bus in self.hpmicro_i2cbus:
            if len(bus) != 13:
                self.error(f"Badly formed HPMICRO_I2CBUS line {bus} {len(bus)=}")
            (port, sda, scl, sda_af, scl_af, sda_paf, scl_paf, sda_baf, scl_baf, bus_clock, speed, internal, soft) = bus
            buslist.append(f"{{ .port={port}, .sda={sda}, .scl={scl}, .sda_af={sda_af}, .scl_af={scl_af}, .sda_paf={sda_paf}, .scl_paf={scl_paf}, .sda_baf={sda_baf}, .scl_baf={scl_baf}, .bus_clock={bus_clock}, .speed={speed}, .internal={internal}, .soft={soft} }}")

        self.write_device_table(f, "i2c buses", "HAL_HPM_I2C_BUSES", buslist)

    # HPMICRO_SPI_BUS support:
    def process_line_hpmicro_spibus(self, line, depth, a):
        self.hpmicro_spibus.append(a[1:])

    def SPI_config_define_line_for_dev(self, define_name, dev, n):
        '''return a #define line for a HPMICRO_SPIBUS config line'''
        (host, dma_ch, mosi, miso, sclk) = dev
        return "{{ .host={host}, .dma_ch={dma_ch}, .mosi={mosi}, .miso={miso}, .sclk={sclk} }},"

    def write_SPI_bus_table(self, f):
        '''write SPI bus table'''
        buslist = []
        for bus in self.hpmicro_spibus:
            if len(bus) != 20:
                self.error(f"Badly formed HPMICRO_SPIBUS line {bus} {len(bus)=}")
            (host, host_clk, dmabase, dma_irqn, dma_ch_tx, dma_tx_src, dma_ch_rx, dma_rx_src, mosi, miso, sclk, mosi_af, miso_af, sclk_af, mosi_baf, miso_baf, sclk_baf, mosi_paf, miso_paf, sclk_paf) = bus
            buslist.append(f"{{ .host={host}, .host_clk={host_clk}, .dma={dmabase}, .dma_irqn={dma_irqn}, .dma_ch_tx={dma_ch_tx}, .dma_tx_src={dma_tx_src}, .dma_ch_rx={dma_ch_rx}, .dma_rx_src={dma_rx_src}, .mosi={mosi}, .miso={miso}, .sclk={sclk}, .mosi_af={mosi_af}, .miso_af={miso_af}, .sclk_af={sclk_af}, .mosi_baf={mosi_baf}, .miso_baf={miso_baf}, .sclk_baf={sclk_baf}, .mosi_paf={mosi_paf}, .miso_paf={miso_paf}, .sclk_paf={sclk_paf} }}")

        self.write_device_table(f, "SPI buses", "HAL_HPM_SPI_BUSES", buslist)

    def process_line_hpmicro_spidev(self, line, depth, a):
        self.hpmicro_spidev.append(a[1:])

    def process_line_hpmicro_serial(self, line, depth, a):
        self.hpmicro_serials.append(a[1:])

    def process_line_hpmicro_can(self, line, depth, a):
        self.hpmicro_can.append(a[1:])

    def process_line_hpmicro_adc(self, line, depth, a):
        self.hpmicro_adc.append(a[1:])

    def process_line_hpmicro_gpio(self, line, depth, a):
        self.hpmicro_gpio.append(a[1:])

    # HPMICRO_RCOUT support:
    def process_line_hpmicro_rcout(self, line, depth, a):
        self.hpmicro_rcout.append(a[1:])

    def write_SPI_device_table(self, f):
        '''write SPI device table'''
        devlist = []
        for dev in self.hpmicro_spidev:
            if len(dev) != 10:
                self.error(f"Badly formed HPMICRO_SPIDEV line {dev} {len(dev)=}")
            (name, bus, device, cs, af, baf, paf, mode, lowspeed, highspeed) = dev
            if not re.match(r"^\d+$", bus):
                raise ValueError(f"Bad HPMICRO_SPIDEV bus ({bus}) (must be digits)")
            if not re.match(r"^\d+$", device):
                raise ValueError(f"Bad HPMICRO_SPIDEV device ({device}) (must be digits)")
            if not re.match(r"^\w+$", cs):
                raise ValueError(f"Bad HPMICRO_SPIDEV cs ({cs}) (must be word characters)")
            if not re.match(r"^\d+$", mode):
                raise ValueError(f"Bad HPMICRO_SPIDEV mode ({mode}) (must be digits)")
            if not lowspeed.endswith('*MHZ') and not lowspeed.endswith('*KHZ'):
                self.error("Bad lowspeed value %s in HPMICRO_SPIDEV line %s" % (lowspeed, dev))
            if not highspeed.endswith('*MHZ') and not highspeed.endswith('*KHZ'):
                self.error("Bad highspeed value %s in HPMICRO_SPIDEV line %s" %
                           (highspeed, dev))
            devlist.append(f"{{.name= \"{name}\", .bus={bus}, .device={device}, .cs={cs}, .af={af}, .baf={baf}, .paf={paf}, .mode={mode}, .lspeed={lowspeed}, .hspeed={highspeed}}}")  # noqa:E501

        self.write_device_table(f, 'SPI devices', 'HAL_HPM_SPI_DEVICES', devlist)

    def write_I2C_config(self, f):
        '''write I2C config defines'''

        self.write_I2C_bus_table(f)

    def write_SPI_config(self, f):
        '''write SPI config defines'''

        if len(self.hpmicro_spibus):
            self.write_SPI_bus_table(f)

        if len(self.hpmicro_spidev):
            self.write_SPI_device_table(f)

    def write_SERIAL_config(self, f):
        '''write serial config defines'''

        seriallist = []
        for serial in self.hpmicro_serials:
            if len(serial) == 12:
                (port, clk, rxpin, txpin, rx_af, tx_af, rx_baf, tx_baf, rx_paf, tx_paf, irq_num, idx) = serial
                cts = '0'
                rts = '0'
                cts_af = '0'
                rts_af = '0'
                cts_baf = '0'
                rts_baf = '0'
                cts_paf = '0'
                rts_paf = '0'
            elif len(serial) == 20:
                (port, clk, rxpin, txpin, rx_af, tx_af, rx_baf, tx_baf, rx_paf, tx_paf, irq_num, idx,
                 cts, rts, cts_af, rts_af, cts_baf, rts_baf, cts_paf, rts_paf) = serial
            else:
                self.error(f"Badly formed HPMICRO_SERIAL line {serial} {len(serial)=}")
            seriallist.append(
                f"{{ .port={port}, .clk={clk}, .rx={rxpin}, .tx={txpin}, .rx_af={rx_af}, .tx_af={tx_af}, .rx_baf={rx_baf}, .tx_baf={tx_baf}, .rx_paf={rx_paf}, .tx_paf={tx_paf}, .irq_num={irq_num}, .idx={idx}, .cts={cts}, .rts={rts}, .cts_af={cts_af}, .rts_af={rts_af}, .cts_baf={cts_baf}, .rts_baf={rts_baf}, .cts_paf={cts_paf}, .rts_paf={rts_paf} }}")

        self.write_device_table(f, 'serial devices', 'HAL_HPM_UART_DEVICES', seriallist)

    def write_CAN_config(self, f):
        '''write CAN config defines'''
        canlist = []
        clocklist = []
        can_order = []
        can_rev_order = []
        for can in self.hpmicro_can:
            (idx,rx_ioc, tx_ioc, rx_af, rx_baf, rx_paf, tx_af, tx_baf, tx_paf, irqn, clock) = can
            canlist.append(f"{{.base = HPM_CAN{idx}, .idx={idx}, .rx_ioc={rx_ioc}, .tx_ioc={tx_ioc}, .rx_af={rx_af}, .rx_baf={rx_baf}, .rx_paf={rx_paf}, .tx_af={tx_af}, .tx_baf={tx_baf}, .tx_paf={tx_paf}, .irqn={irqn}, .clock={clock} }}")
            clocklist.append(f"clock_can{idx}")
            can_order.append(int(idx))  # 添加实际的整数值而不是格式化字符串
            can_rev_order.append(int(idx))  # 添加实际的整数值而不是格式化字符串
    
        self.write_device_table(f, 'CAN devices', 'HAL_CAN_BUS_DESC_LIST', canlist)
        self.write_device_table(f, 'CAN devices', 'HAL_CAN_CLOCK_LIST', clocklist)
    
        for i in can_order:
            f.write("#define HAL_CAN_IFACE%u_ENABLE\n" % i)
        f.write('#define HAL_CAN_INTERFACE_LIST %s\n' % ','.join([str(i) for i in can_order]))
        f.write('#define HAL_CAN_INTERFACE_REV_LIST %s\n' % ','.join([str(i) for i in can_rev_order]))
        f.write('#define HAL_NUM_CAN_IFACES %d\n' % len(canlist))
        self.env_vars['HAL_NUM_CAN_IFACES'] = str(len(canlist))

    def write_ADC_config(self, f):
        '''write ADC config defines'''

        adc_list = []
        for adc in self.hpmicro_adc:
            if len(adc) != 7:
                self.error(f"Badly formed HPMICRO_ADC line {adc} {len(adc)=}")
            (channel, scaling, ardupin, pin, is_adc16, host_base, clk) = adc
            adc_list.append(f"{{.channel = {channel}, .scaling = {scaling}, .ardupin = {ardupin}, .pin = {pin}, .is_adc16 = {is_adc16}, .host = {{.base = (uint32_t){host_base}}}, .clk = {clk},}}")

        self.write_device_table(f, 'ADC devices', 'HAL_HPM_ADC_PINS', adc_list)

    def write_GPIO_config(self, f):
        '''write GPIO config defines'''

        gpio_list = []
        for gpio in self.hpmicro_gpio:
            if len(gpio) != 6:
                self.error(f"Badly formed HPMICRO_GPIO line {gpio} {len(gpio)=}")
            (pin_num, ioc_idx, enabled, pwm_num, pal_line, fn) = gpio
            gpio_list.append(f"{{.pin_num = {pin_num}, .ioc_idx = {ioc_idx}, .enabled = {enabled}, .pwm_num = {pwm_num}, .pal_line = {pal_line}, .fn = nullptr,}}")

        self.write_device_table(f, 'GPIO devices', 'HAL_GPIO_PINS', gpio_list)

    def write_RCOUT_config(self, f):
        '''write rc output defines'''
        rcout_list = []
        for rcout in self.hpmicro_rcout:
            if len(rcout) != 2:
                self.error(f"Badly formed HPMICRO_RCOUT line {rcout} {len(rcout)=}")
            (pin_index, pwm_port_index, ) = rcout
            rcout_list.append(f"{{.pin_index = {pin_index}, .pwm_port_index = {pwm_port_index}, }}")

        if len(rcout_list) == 0:
            f.write("// No rc outputs\n")
            return
        self.write_device_table(f, 'RCOUT devices', 'HAL_HPM_RCOUT', rcout_list)

    def process_file(self, filename, depth=0):
        '''process a hwdef.dat file'''
        self.loaded_files.add(os.path.abspath(filename))
        try:
            f = open(filename, "r")
        except Exception as e:
            if False:
                raise e
            self.error("Unable to open file %s" % filename)
        for line in f.readlines():
            line = line.split('#')[0] # ensure we discard the comments
            line = line.strip()
            if len(line) == 0 or line[0] == '#':
                continue
            a = shlex.split(line)
            if a[0] == "include" and len(a) > 1:
                include_file = a[1]
                if include_file[0] != '/':
                    dir = os.path.dirname(filename)
                    include_file = os.path.normpath(
                        os.path.join(dir, include_file))
                self.process_file(include_file, depth+1)
            else:
                self.process_line(line, depth)

    def process_hwdefs(self):
        for fname in self.hwdef:
            self.process_file(fname)
        self.processed_hwdefs = True

    def run(self):
        # process input file
        self.process_hwdefs()

        # write out hwdef.h
        self.write_hwdef_header(self.get_output_path("hwdef.h"))

if __name__ == '__main__':

    parser = argparse.ArgumentParser("hpmicro_hwdef.py")
    parser.add_argument(
        '-D', '--outdir', type=str, default="/tmp", help='Output directory')
    parser.add_argument(
        'hwdef', type=str, nargs='+', default=None, help='hardware definition file')
    parser.add_argument(
        '--quiet', action='store_true', default=False, help='quiet running')

    args = parser.parse_args()

    c = HPMicroHWDef(
        outdir=args.outdir,
        hwdef=args.hwdef,
        quiet=args.quiet,
    )
    c.run()
