#pragma once
#include <hwdef.h>
#define HAL_BOARD_NAME "HPMICRO"
#define HAL_CPU_CLASS HAL_CPU_CLASS_150
#define HAL_MEM_CLASS HAL_MEM_CLASS_1000
#ifndef HAL_STORAGE_SIZE
#define HAL_STORAGE_SIZE            16384
#endif
#define HAL_STORAGE_SIZE_AVAILABLE  HAL_STORAGE_SIZE
#define HAL_INS_DEFAULT HAL_INS_NONE

#ifndef HAL_PROGRAM_SIZE_LIMIT_KB
#define HAL_PROGRAM_SIZE_LIMIT_KB 2048
#endif

#ifndef CONFIG_HAL_BOARD_SUBTYPE
#define CONFIG_HAL_BOARD_SUBTYPE  1
#endif
#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_HPMPILOTBF67
#include "hpmpilotbf67.h"
#endif
#if CONFIG_HAL_BOARD_SUBTYPE == HAL_BOARD_SUBTYPE_HPM6750EVKMINI
#include "hpm6750evkmini.h"
#endif
#ifndef HAL_BOARD_STATE_DIRECTORY
#define HAL_BOARD_STATE_DIRECTORY "/SDCARD/APM"
#endif

#ifndef HAL_BOARD_LOG_DIRECTORY
#define HAL_BOARD_LOG_DIRECTORY HAL_BOARD_STATE_DIRECTORY "/LOGS"
#endif

#ifndef HAL_BOARD_TERRAIN_DIRECTORY
#define HAL_BOARD_TERRAIN_DIRECTORY HAL_BOARD_STATE_DIRECTORY "/TERRAIN"
#endif

#ifndef HAL_BOARD_STORAGE_DIRECTORY
#define HAL_BOARD_STORAGE_DIRECTORY HAL_BOARD_STATE_DIRECTORY "/STORAGE"
#endif


#define HAL_HAVE_BOARD_VOLTAGE 0
#define HAL_HAVE_SERVO_VOLTAGE 0
#define HAL_HAVE_SAFETY_SWITCH 1

#define AP_INERTIALSENSOR_ALLOW_NO_SENSORS   1

#define HAL_Semaphore HPMicro::Semaphore
#define HAL_BinarySemaphore HPMicro::BinarySemaphore
#ifdef __cplusplus
#include <AP_Common/AP_Common.h>
#include <AP_HAL_HPMICRO/Semaphores.h>
#endif
